# Generated by Django 3.1.2 on 2020-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('salary', models.CharField(choices=[('100.0', '100.0'), ('200.0', '200.0'), ('300.0', '300.0'), ('400.0', '400.0')], max_length=300)),
                ('position', models.CharField(choices=[('level 1', 'level 1'), ('level 2', 'level 2'), ('level 3', 'level 3'), ('level 4', 'level 4'), ('level 5', 'level 5'), ('level 6', 'level 6'), ('level 7', 'level 7'), ('level 8', 'level 9'), ('level 9', 'level 9'), ('level 10', 'level 10')], max_length=300)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
