# Generated by Django 3.1.2 on 2020-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201030_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('level 1', 'level 1'), ('level 2', 'level 2'), ('level 3', 'level 3'), ('level 4', 'level 4'), ('level 5', 'level 5'), ('level 6', 'level 6'), ('level 7', 'level 7'), ('level 8', 'level 9'), ('level 9', 'level 9'), ('level 10', 'level 10')], max_length=300),
        ),
    ]
